### PR TITLE
RST-116 Changing angular velocity sign.

### PR DESCRIPTION
**Pull request by ayrton04**
@locusrobotics/robot-software-team 

Can someone try running this in indigo to make sure it behaves?

### CODE REVIEW

**Comment by tappan-at-git** [comment]
Building to test.

**Comment by tappan-at-git** [comment]
Looks good! Are we simulating caster snap now? I was getting what looked like small changes in orientation when switching between +x and -x motion.

**Review by tappan-at-git — APPROVED** [review]

**Comment by ayrton04** [comment]
We have casters, but they are not hinged, and are just modelled as spheres.

**Comment by tappan-at-git** [comment]
That's strange, then. It's a small enough shift that I'm not sure if I'm imagining it, at least, and it's not like we actually back up outside of teleop.

**Review by davelkan-zz — APPROVED** [review]

**Pull request merged**
