### PR TITLE
Adding static covariances per issue #5

### PR DESCRIPTION
**Pull request by ayrton04**
This addresses #5. FYI @bradleypowers @tappan-at-git @kayak0806 @davelkan

### CODE REVIEW

**Comment by tappan-at-git** [comment]
Looks solid. Have you tested dynamic covariances with your change to the yaw covariance (multiplying by the time step)? It's consistent with all the other covariances (which were multiplying by the time step even before this PR), so it definitely seems like it should work.

**Comment by ayrton04** [comment]
It works, but the use case of increasing yaw covariance when we have perfect localization is not what we want. The error will keep growing on yaw and the filter will trust it less over time, making yaw laggy.

**Comment by tappan-at-git** [comment]
:+1:

**Comment by bradleypowers** [comment]
LGTM.

**Pull request merged**
